import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "../components/SessionProviderWrapper";
import Header from "../components/Header";  // Header import edildi

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`} // arka plan ve minimum yükseklik eklendi
      >
        <SessionProviderWrapper>
          <Header />   {/* Header burada */}
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
